/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chatbot: typeof import('./src/components/dashboard/Chatbot.vue')['default']
    CreateTicket: typeof import('./src/components/dashboard/CreateTicket.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    Navbar: typeof import('./src/components/navbar/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ViewTicket: typeof import('./src/components/dashboard/ViewTicket.vue')['default']
  }
}
