/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BubbleChart: typeof import('./src/components/charts/BubbleChart.vue')['default']
    Chatbot: typeof import('./src/components/dashboard/Chatbot.vue')['default']
    ChoroplethMapChart: typeof import('./src/components/charts/ChoroplethMapChart.vue')['default']
    ContextMenuCheckboxItem: typeof import('reka-ui')['ContextMenuCheckboxItem']
    ContextMenuContent: typeof import('reka-ui')['ContextMenuContent']
    ContextMenuItem: typeof import('reka-ui')['ContextMenuItem']
    ContextMenuItemIndicator: typeof import('reka-ui')['ContextMenuItemIndicator']
    ContextMenuLabel: typeof import('reka-ui')['ContextMenuLabel']
    ContextMenuPortal: typeof import('reka-ui')['ContextMenuPortal']
    ContextMenuRadioGroup: typeof import('reka-ui')['ContextMenuRadioGroup']
    ContextMenuRadioItem: typeof import('reka-ui')['ContextMenuRadioItem']
    ContextMenuRoot: typeof import('reka-ui')['ContextMenuRoot']
    ContextMenuSeparator: typeof import('reka-ui')['ContextMenuSeparator']
    ContextMenuSub: typeof import('reka-ui')['ContextMenuSub']
    ContextMenuSubContent: typeof import('reka-ui')['ContextMenuSubContent']
    ContextMenuSubTrigger: typeof import('reka-ui')['ContextMenuSubTrigger']
    ContextMenuTrigger: typeof import('reka-ui')['ContextMenuTrigger']
    CreateTicket: typeof import('./src/components/dashboard/CreateTicket.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    InsightsCard: typeof import('./src/components/cards/InsightsCard.vue')['default']
    LineChart: typeof import('./src/components/charts/LineChart.vue')['default']
    MapBubbleChart: typeof import('./src/components/charts/MapBubbleChart.vue')['default']
    Navbar: typeof import('./src/components/navbar/Navbar.vue')['default']
    PieChart: typeof import('./src/components/charts/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollAreaCorner: typeof import('reka-ui')['ScrollAreaCorner']
    ScrollComments: typeof import('./src/components/cards/ScrollComments.vue')['default']
    StatCard: typeof import('./src/components/cards/StatCard.vue')['default']
    VerticalBarChart: typeof import('./src/components/charts/VerticalBarChart.vue')['default']
    ViewTicket: typeof import('./src/components/dashboard/ViewTicket.vue')['default']
  }
}
